import type { PropertyListing, RentalApplication, LeaseAgreement, PaymentRecord, MaintenanceRequest, TenancyDispute } from '@/types/tenant';

export const INITIAL_PROPERTIES: PropertyListing[] = [
  {
    id: 'prop-ktm-001',
    title: 'Sanepa Heights Executive Residence',
    description: 'Boutique architectural apartment complex located in diplomatic Sanepa, Patan. Features private balconies, uninterrupted 24/7 solar-backed electricity, treated deep-boring water, and seismic structural certification.',
    address: 'Ward 2, Sanepa Road, Patan, Lalitpur (near British School)',
    city: 'Lalitpur',
    postalCode: '44700',
    location: { latitude: 27.6833, longitude: 85.3092 },
    totalFloors: 5,
    landlord: {
      id: 'landlord-001',
      name: 'Property Landlord',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
      phone: '+977-9841234567',
      isVerified: true,
      rating: 4.9,
      responseTime: 'Within 1 hour',
    },
    availableUnitsCount: 2,
    minMonthlyRent: 38000,
    maxMonthlyRent: 55000,
    coverPhotoUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    photos: [
      { id: 'p1', url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80', isCover: true, caption: 'Building Exterior' },
      { id: 'p2', url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80', isCover: false, caption: 'Spacious Sunlit Living Area' },
      { id: 'p3', url: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=1200&q=80', isCover: false, caption: 'Modular Kitchen with Chimney' },
      { id: 'p4', url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80', isCover: false, caption: 'Master Bedroom with Parquet Flooring' },
    ],
    amenities: [
      { id: 'am-1', name: '24/7 Treated Water', slug: 'water', category: 'building', icon: 'droplet' },
      { id: 'am-2', name: 'Dedicated Car Parking', slug: 'parking', category: 'building', icon: 'car' },
      { id: 'am-3', name: 'Solar Backup Power', slug: 'backup', category: 'building', icon: 'zap' },
      { id: 'am-4', name: 'Fiber Optical Internet', slug: 'wifi', category: 'unit', icon: 'wifi' },
      { id: 'am-5', name: 'Elevator & CCTV', slug: 'elevator', category: 'building', icon: 'shield' },
      { id: 'am-6', name: 'Pet Friendly', slug: 'pet', category: 'general', icon: 'heart' },
    ],
    units: [
      {
        id: 'unit-sanepa-101',
        propertyId: 'prop-ktm-001',
        unitIdentifier: 'Unit 201 (South Facing)',
        floorNumber: 2,
        bedrooms: 2,
        bathrooms: 2,
        areaSqft: 980,
        monthlyRent: 42000,
        securityDeposit: 84000,
        availabilityStatus: 'AVAILABLE',
        amenities: [
          { id: 'uam-1', name: 'Private Balcony', slug: 'balcony', category: 'unit' },
          { id: 'uam-2', name: 'Built-in Wardrobes', slug: 'wardrobe', category: 'unit' },
          { id: 'uam-3', name: 'Hot Water Geyser', slug: 'geyser', category: 'unit' },
        ],
        photos: [],
      },
      {
        id: 'unit-sanepa-102',
        propertyId: 'prop-ktm-001',
        unitIdentifier: 'Unit 302 (Corner Suite)',
        floorNumber: 3,
        bedrooms: 3,
        bathrooms: 3,
        areaSqft: 1350,
        monthlyRent: 55000,
        securityDeposit: 110000,
        availabilityStatus: 'AVAILABLE',
        amenities: [
          { id: 'uam-4', name: 'Dual Balconies', slug: 'balcony', category: 'unit' },
          { id: 'uam-5', name: 'Bathtub & Shower Enclosure', slug: 'bath', category: 'unit' },
        ],
        photos: [],
      },
    ],
    verificationBadges: [
      { code: 'TITLE_DEED_VERIFIED', name: 'Title Deed Verified', description: 'Property ownership confirmed through Kathmandu Land Registry.' },
      { code: 'SAFETY_INSPECTED', name: 'Safety Inspected', description: 'Certified structural integrity & emergency fire compliance.' },
    ],
    reviewsSummary: { averageRating: 4.9, totalReviews: 12 },
  },
  {
    id: 'prop-ktm-002',
    title: 'Jhamsikhel Garden Flat',
    description: 'Quiet residential apartment minutes away from Restaurant Street in Patan / Lalitpur. Ground floor with direct access to a private landscaped courtyard, peaceful surroundings, and secure parking.',
    address: 'Jhamsikhel Marg 4, Patan, Lalitpur',
    city: 'Lalitpur',
    postalCode: '44700',
    location: { latitude: 27.6789, longitude: 85.3117 },
    totalFloors: 3,
    landlord: {
      id: 'landlord-002',
      name: 'Sunita Rajbhandari',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=256&q=80',
      phone: '+977-9851098765',
      isVerified: true,
      rating: 4.8,
      responseTime: 'Under 30 mins',
    },
    availableUnitsCount: 1,
    minMonthlyRent: 28000,
    maxMonthlyRent: 28000,
    coverPhotoUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    photos: [
      { id: 'p201', url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80', isCover: true, caption: 'Courtyard & Building Exterior' },
      { id: 'p202', url: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=1200&q=80', isCover: false, caption: 'Warm Living Room' },
      { id: 'p203', url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80', isCover: false, caption: 'Cozy Bedroom' },
    ],
    amenities: [
      { id: 'am-1', name: '24/7 Treated Water', slug: 'water', category: 'building', icon: 'droplet' },
      { id: 'am-2', name: 'Bike & Car Parking', slug: 'parking', category: 'building', icon: 'car' },
      { id: 'am-4', name: 'High-Speed Wi-Fi', slug: 'wifi', category: 'unit', icon: 'wifi' },
      { id: 'am-6', name: 'Pet Friendly', slug: 'pet', category: 'general', icon: 'heart' },
    ],
    units: [
      {
        id: 'unit-jham-01',
        propertyId: 'prop-ktm-002',
        unitIdentifier: 'Flat 1A (Ground Level)',
        floorNumber: 1,
        bedrooms: 2,
        bathrooms: 1,
        areaSqft: 750,
        monthlyRent: 28000,
        securityDeposit: 56000,
        availabilityStatus: 'AVAILABLE',
        amenities: [],
        photos: [],
      },
    ],
    verificationBadges: [
      { code: 'IDENTITY_VERIFIED', name: 'Verified Landlord', description: 'Landlord identity & citizenship verified.' },
    ],
    reviewsSummary: { averageRating: 4.8, totalReviews: 8 },
  },
  {
    id: 'prop-ktm-003',
    title: 'Lazimpat Embassy Quarter Apartment',
    description: 'Chic modern apartment in prime Lazimpat, walking distance from Radisson Hotel and Narayanhiti museum. Generous natural light, modular kitchenette, inverter backup, and gated entrance.',
    address: 'Lazimpat, Lane 5, Kathmandu',
    city: 'Kathmandu',
    postalCode: '44600',
    location: { latitude: 27.7214, longitude: 85.3189 },
    totalFloors: 4,
    landlord: {
      id: 'landlord-003',
      name: 'Pradeep Shrestha',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
      phone: '+977-9801239988',
      isVerified: true,
      rating: 4.7,
      responseTime: 'Same day',
    },
    availableUnitsCount: 2,
    minMonthlyRent: 22000,
    maxMonthlyRent: 35000,
    coverPhotoUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',
    photos: [
      { id: 'p301', url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80', isCover: true, caption: 'Modern Studio Living' },
      { id: 'p302', url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80', isCover: false, caption: 'Dining & Kitchenette' },
    ],
    amenities: [
      { id: 'am-1', name: '24/7 Water Supply', slug: 'water', category: 'building', icon: 'droplet' },
      { id: 'am-2', name: 'Motorbike Parking', slug: 'parking', category: 'building', icon: 'car' },
      { id: 'am-3', name: 'Power Backup', slug: 'backup', category: 'building', icon: 'zap' },
      { id: 'am-4', name: 'High-Speed Wi-Fi', slug: 'wifi', category: 'unit', icon: 'wifi' },
    ],
    units: [
      {
        id: 'unit-laz-101',
        propertyId: 'prop-ktm-003',
        unitIdentifier: 'Studio 2B',
        floorNumber: 2,
        bedrooms: 1,
        bathrooms: 1,
        areaSqft: 480,
        monthlyRent: 22000,
        securityDeposit: 44000,
        availabilityStatus: 'AVAILABLE',
        amenities: [],
        photos: [],
      },
      {
        id: 'unit-laz-102',
        propertyId: 'prop-ktm-003',
        unitIdentifier: 'Flat 3A',
        floorNumber: 3,
        bedrooms: 2,
        bathrooms: 1,
        areaSqft: 800,
        monthlyRent: 35000,
        securityDeposit: 70000,
        availabilityStatus: 'AVAILABLE',
        amenities: [],
        photos: [],
      },
    ],
    verificationBadges: [
      { code: 'TITLE_DEED_VERIFIED', name: 'Title Deed Verified', description: 'Legally documented rental ownership.' },
    ],
    reviewsSummary: { averageRating: 4.7, totalReviews: 19 },
  },
  {
    id: 'prop-ktm-004',
    title: 'Baluwatar Prime Diplomatic Suite',
    description: 'Executive family apartment in high-security Baluwatar zone. Double glazing windows, central hot water, backup generator, video intercom, and on-site guard 24/7.',
    address: 'Baluwatar Road (near Russian Embassy)',
    city: 'Kathmandu',
    postalCode: '44600',
    location: { latitude: 27.7285, longitude: 85.3289 },
    totalFloors: 6,
    landlord: {
      id: 'landlord-004',
      name: 'Ramesh Karki',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
      phone: '+977-9812345678',
      isVerified: true,
      rating: 5.0,
      responseTime: 'Within 15 mins',
    },
    availableUnitsCount: 1,
    minMonthlyRent: 65000,
    maxMonthlyRent: 65000,
    coverPhotoUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    photos: [
      { id: 'p401', url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80', isCover: true, caption: 'Facade & Parking' },
      { id: 'p402', url: 'https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1200&q=80', isCover: false, caption: 'Luxury Living Space' },
      { id: 'p403', url: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80', isCover: false, caption: 'Modern Master Ensuite' },
    ],
    amenities: [
      { id: 'am-1', name: '24/7 Water & Filter', slug: 'water', category: 'building', icon: 'droplet' },
      { id: 'am-2', name: '2 Covered Parking Slots', slug: 'parking', category: 'building', icon: 'car' },
      { id: 'am-3', name: 'Diesel Generator Backup', slug: 'backup', category: 'building', icon: 'zap' },
      { id: 'am-4', name: 'Fiber Internet 300 Mbps', slug: 'wifi', category: 'unit', icon: 'wifi' },
      { id: 'am-5', name: 'Automatic Elevator', slug: 'elevator', category: 'building', icon: 'shield' },
    ],
    units: [
      {
        id: 'unit-bal-401',
        propertyId: 'prop-ktm-004',
        unitIdentifier: 'Penthouse Unit 501',
        floorNumber: 5,
        bedrooms: 3,
        bathrooms: 3,
        areaSqft: 1650,
        monthlyRent: 65000,
        securityDeposit: 130000,
        availabilityStatus: 'AVAILABLE',
        amenities: [],
        photos: [],
      },
    ],
    verificationBadges: [
      { code: 'TITLE_DEED_VERIFIED', name: 'Title Deed Verified', description: 'Verified clean ownership title.' },
      { code: 'SAFETY_INSPECTED', name: 'Seismic Tested', description: 'Engineered post-earthquake reinforcement.' },
    ],
    reviewsSummary: { averageRating: 5.0, totalReviews: 6 },
  },
  {
    id: 'prop-ktm-005',
    title: 'Boudha Serene Stupa View Flat',
    description: 'Serene flat situated 5 minutes from Boudhanath Stupa in a tranquil cul-de-sac. Features south-facing sunlight, rooftop terrace access, solar water heating, and high-speed Wi-Fi.',
    address: 'Boudha, Tusal Chowk, Kathmandu',
    city: 'Kathmandu',
    postalCode: '44600',
    location: { latitude: 27.7215, longitude: 85.3619 },
    totalFloors: 3,
    landlord: {
      id: 'landlord-005',
      name: 'Tsering Lama',
      avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
      phone: '+977-9849887766',
      isVerified: true,
      rating: 4.9,
      responseTime: 'Under 1 hour',
    },
    availableUnitsCount: 1,
    minMonthlyRent: 26000,
    maxMonthlyRent: 26000,
    coverPhotoUrl: 'https://images.unsplash.com/photo-1502005229762-ee1b2b93e08f?auto=format&fit=crop&w=1200&q=80',
    photos: [
      { id: 'p501', url: 'https://images.unsplash.com/photo-1502005229762-ee1b2b93e08f?auto=format&fit=crop&w=1200&q=80', isCover: true, caption: 'Sunny Terrace & Living' },
      { id: 'p502', url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80', isCover: false, caption: 'Bright Kitchen Area' },
    ],
    amenities: [
      { id: 'am-1', name: '24/7 Water Supply', slug: 'water', category: 'building', icon: 'droplet' },
      { id: 'am-2', name: 'Bike Parking', slug: 'parking', category: 'building', icon: 'car' },
      { id: 'am-4', name: 'Fiber Wi-Fi', slug: 'wifi', category: 'unit', icon: 'wifi' },
      { id: 'am-6', name: 'Balcony & Roof Access', slug: 'balcony', category: 'unit', icon: 'sun' },
    ],
    units: [
      {
        id: 'unit-boudha-201',
        propertyId: 'prop-ktm-005',
        unitIdentifier: 'Flat 2B (Upper Level)',
        floorNumber: 2,
        bedrooms: 2,
        bathrooms: 1,
        areaSqft: 720,
        monthlyRent: 26000,
        securityDeposit: 52000,
        availabilityStatus: 'AVAILABLE',
        amenities: [],
        photos: [],
      },
    ],
    verificationBadges: [
      { code: 'IDENTITY_VERIFIED', name: 'Verified Landlord', description: 'Registered landlord verified.' },
    ],
    reviewsSummary: { averageRating: 4.9, totalReviews: 15 },
  },
  {
    id: 'prop-ktm-006',
    title: 'Bhaktapur Heritage Brick Cottage',
    description: 'Renovated traditional brick townhouse with modern interior fittings near Dattatreya Square. Wooden beams, modern plumbing, solar water heating, and fiber internet.',
    address: 'Suryabinayak / Dattatreya Marg, Bhaktapur',
    city: 'Bhaktapur',
    postalCode: '44800',
    location: { latitude: 27.6722, longitude: 85.4280 },
    totalFloors: 3,
    landlord: {
      id: 'landlord-006',
      name: 'Nabin Prajapati',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
      phone: '+977-9860112233',
      isVerified: true,
      rating: 4.8,
      responseTime: 'Within 2 hours',
    },
    availableUnitsCount: 1,
    minMonthlyRent: 18000,
    maxMonthlyRent: 18000,
    coverPhotoUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    photos: [
      { id: 'p601', url: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80', isCover: true, caption: 'Brickwork Architecture' },
    ],
    amenities: [
      { id: 'am-1', name: 'Filtered Water System', slug: 'water', category: 'building', icon: 'droplet' },
      { id: 'am-4', name: 'High-Speed Wi-Fi', slug: 'wifi', category: 'unit', icon: 'wifi' },
    ],
    units: [
      {
        id: 'unit-bhak-101',
        propertyId: 'prop-ktm-006',
        unitIdentifier: 'Townhouse Unit 1',
        floorNumber: 1,
        bedrooms: 2,
        bathrooms: 1,
        areaSqft: 680,
        monthlyRent: 18000,
        securityDeposit: 36000,
        availabilityStatus: 'AVAILABLE',
        amenities: [],
        photos: [],
      },
    ],
    verificationBadges: [
      { code: 'TITLE_DEED_VERIFIED', name: 'Title Deed Verified', description: 'Ownership verified.' },
    ],
    reviewsSummary: { averageRating: 4.8, totalReviews: 5 },
  },
];

export const INITIAL_SAVED_PROPERTY_IDS: string[] = ['prop-ktm-001', 'prop-ktm-003'];

export const INITIAL_APPLICATIONS: RentalApplication[] = [
  {
    id: 'app-rh-2026-001',
    unitId: 'unit-sanepa-101',
    propertyId: 'prop-ktm-001',
    tenantId: 'user-tenant-current',
    landlordId: 'landlord-001',
    status: 'approved',
    message: 'Hello Mr. Thapa, I am a software engineer working remotely. Looking for a peaceful 2-BHK for a long-term 1-year tenancy starting from next month.',
    proposedMoveIn: '2026-10-15',
    createdAt: '2026-09-24T10:30:00Z',
    updatedAt: '2026-09-26T14:15:00Z',
    unit: {
      id: 'unit-sanepa-101',
      unitIdentifier: 'Unit 201 (South Facing)',
      floorNumber: 2,
      bedrooms: 2,
      bathrooms: 2,
      monthlyRent: 42000,
      securityDeposit: 84000,
    },
    property: {
      id: 'prop-ktm-001',
      title: 'Sanepa Heights Executive Residence',
      address: 'Ward 2, Sanepa Road, Lalitpur',
      city: 'Lalitpur',
      coverPhotoUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=600&q=80',
    },
    landlord: {
      id: 'landlord-001',
      name: 'Property Landlord',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
      phone: '+977-9841234567',
    },
  },
];

export const INITIAL_ACTIVE_LEASE: LeaseAgreement = {
  id: 'lease-rh-2026-99',
  unitId: 'unit-sanepa-101',
  propertyId: 'prop-ktm-001',
  tenantId: 'user-tenant-current',
  landlordId: 'landlord-001',
  rentalRequestId: 'app-rh-2026-001',
  status: 'active',
  startDate: '2026-04-01',
  endDate: '2027-03-31',
  agreedMonthlyRent: 42000,
  agreedDeposit: 84000,
  tenantSignedAt: '2026-03-28T09:12:00Z',
  landlordSignedAt: '2026-03-28T11:45:00Z',
  signedAt: '2026-03-28T11:45:00Z',
  terminatedAt: null,
  createdAt: '2026-03-25T14:00:00Z',
  updatedAt: '2026-03-28T11:45:00Z',
  propertyTitle: 'Sanepa Heights Executive Residence',
  propertyAddress: 'Ward 2, Sanepa Road (near British School)',
  propertyCity: 'Lalitpur',
  unitIdentifier: 'Unit 201 (South Facing)',
  landlordName: 'Property Landlord',
  landlordPhone: '+977-9841234567',
  tenantName: 'Resident Tenant',
};

export const INITIAL_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-001',
    tenancyId: 'lease-rh-2026-99',
    invoiceNumber: 'INV-2026-09-01',
    billingMonth: 'September 2026',
    dueDate: '2026-09-05',
    paidDate: '2026-09-03',
    amount: 42000,
    type: 'RENT',
    status: 'PAID',
    paymentMethod: 'eSewa',
    transactionId: 'ESEWA-982314569',
  },
  {
    id: 'pay-002',
    tenancyId: 'lease-rh-2026-99',
    invoiceNumber: 'INV-2026-08-01',
    billingMonth: 'August 2026',
    dueDate: '2026-08-05',
    paidDate: '2026-08-04',
    amount: 42000,
    type: 'RENT',
    status: 'PAID',
    paymentMethod: 'ConnectIPS',
    transactionId: 'CIPS-482019481',
  },
  {
    id: 'pay-003',
    tenancyId: 'lease-rh-2026-99',
    invoiceNumber: 'INV-2026-10-01',
    billingMonth: 'October 2026',
    dueDate: '2026-10-05',
    paidDate: null,
    amount: 42000,
    type: 'RENT',
    status: 'PENDING',
  },
];

export const INITIAL_MAINTENANCE: MaintenanceRequest[] = [
  {
    id: 'maint-001',
    tenancyId: 'lease-rh-2026-99',
    unitIdentifier: 'Unit 201',
    propertyTitle: 'Sanepa Heights Executive Residence',
    category: 'Plumbing',
    urgency: 'Medium',
    title: 'Ensuite bathroom mixer tap dripping',
    description: 'The hot water mixer tap in the master bathroom has a slow drip that doesn’t stop after tightening.',
    status: 'IN_PROGRESS',
    preferredTimeWindow: 'Morning (9:00 AM – 12:00 PM)',
    createdAt: '2026-09-25T11:20:00Z',
    scheduledDate: '2026-09-30',
    technicianNotes: 'Plumber scheduled for gasket replacement.',
  },
  {
    id: 'maint-002',
    tenancyId: 'lease-rh-2026-99',
    unitIdentifier: 'Unit 201',
    propertyTitle: 'Sanepa Heights Executive Residence',
    category: 'Electrical',
    urgency: 'High',
    title: 'Inverter changeover switch tripping on load',
    description: 'During scheduled load shedding, the inverter switch clicks twice and trips main MCB.',
    status: 'RESOLVED',
    createdAt: '2026-08-12T08:10:00Z',
    resolvedAt: '2026-08-13T16:00:00Z',
    technicianNotes: 'Replaced faulty 16A breaker in distribution panel. Tested under full load.',
  },
];

export const INITIAL_DISPUTES: TenancyDispute[] = [
  {
    id: 'disp-001',
    tenancyId: 'lease-rh-2026-99',
    raisedById: 'user-tenant-current',
    category: 'PREMISES_ACCESS',
    title: 'Contractor entered terrace without prior 24h notice',
    description: 'Building maintenance crew performed solar panel pressure wash walking past bedroom windows on Saturday morning without written 24-hour advance notification as mandated in Clause 7 of the Tenancy Agreement.',
    claimAmount: 0,
    evidenceUrls: ['https://cdn.example.com/log-notice.pdf'],
    status: 'RESOLVED_MUTUAL',
    resolutionSummary: 'Landlord apologized and formally instructed building management to enforce 48h advance SMS alerts for any terrace works.',
    resolvedAt: '2026-07-20T15:00:00Z',
    createdAt: '2026-07-18T10:00:00Z',
    propertyTitle: 'Sanepa Heights Executive Residence',
    unitIdentifier: 'Unit 201',
  },
];
